api_login:
   path: /token
   methods:  [POST]

gesdinet_jwt_refresh_token:
    path:     /token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
    methods:  [POST]

api:
    type: rest
    resource: "routing_rest.yml"
