<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryAdminUsers()
    {
        return $this->queryBuilderAdminUsers()->getQuery();
    }

    public function queryBuilderAdminUsers()
    {
        return $this->createQueryBuilder('u');
    }
}
