services:
    user.mailer:
        class: UserBundle\Service\Mailer
        public: false
        arguments: ['@mailer', '@twig', { template: { confirmation: '%fos_user.registration.confirmation.template%', resetting: '%fos_user.resetting.email.template%' }, from_email: { register: '%fos_user.registration.confirmation.from_email%', confirmation: '%fos_user.registration.confirmation.from_email%', resetting: '%fos_user.resetting.email.from_email%' } }]

    user.register_listener:
        class: UserBundle\EventListener\RegisterListener
        arguments: ['@user.mailer']
        tags:
            - { name: kernel.event_subscriber }
