services:
    user.mailer:
        class: UserBundle\Service\Mailer
        public: false
        arguments: ['@mailer', '@twig', { template: { confirmation: '%fos_user.registration.confirmation.template%', resetting: '%fos_user.resetting.email.template%' }, from_email: { confirmation: '%fos_user.registration.confirmation.from_email%', resetting: '%fos_user.resetting.email.from_email%' } }]
