<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Garden;
use CoreBundle\Entity\Type;

/**
 * AccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByGardenAndType(Garden $garden, Type $type)
    {
        $qb = $this->createQueryBuilder('a')
                    ->where('a.garden = :garden')
                    ->andWhere('a.type = :type')
                    ->setParameters([
                        'garden' => $garden,
                        'type' => $type,
                    ]);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function measureIsPublic(Garden $garden, Type $type)
    {
        $qb = $this->createQueryBuilder('a')
                    ->select('COUNT(a.id)')
                    ->where('a.garden = :garden')
                    ->andWhere('a.type = :type')
                    ->andWhere('a.isPublic = true')
                    ->setParameters([
                        'garden' => $garden,
                        'type' => $type,
                    ]);

        return (bool) $qb->getQuery()->getSingleScalarResult();
    }
}
