<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Garden;
use CoreBundle\Entity\Type;
use UserBundle\Entity\User;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAlertByGardenAndType(Garden $garden, Type $type)
    {
        $qb = $this->createQueryBuilder('a')
                    ->where('a.garden = :garden')
                    ->andWhere('a.type = :type')
                    ->setParameters([
                        'garden' => $garden,
                        'type' => $type,
                    ]);

        return $qb->getQuery()->getResult();
    }

    public function queryMeAlerts(User $user)
    {
        $qb = $this->createQueryBuilder('a')
                    ->where('a.owner = :user')
                    ->setParameter('user', $user);

        return $qb->getQuery();
    }
}
