<?php

namespace CoreBundle\Repository;
use UserBundle\Entity\User;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @return \Doctrine\ORM\Query
     */
    public function queryMeConfiguration(User $user)
    {
        return $this->queryBuilderMeConfiguration($user)->getQuery();
    }

    /**
     * @param User $user
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function queryBuilderMeConfiguration(User $user)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.owner = :user')
            ->setParameter('user', $user);

        return $qb;
    }
}
