<?php

namespace CoreBundle\Repository;

/**
 * GardenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GardenRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryPublicGarden()
    {
        $qb = $this->createQueryBuilder('g')
                    ->where('g.isPublic = true');

        return $qb->getQuery();
    }
}
