<?php

namespace CoreBundle\Repository;

use UserBundle\Entity\User;

/**
 * GardenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GardenRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryPublicGardens()
    {
        return $this->queryBuilderPublicGardens()->getQuery();
    }

    public function queryMeGardens(User $user)
    {
        $qb = $this->createQueryBuilder('g')
                    ->where('g.owner = :user')
                    ->setParameter('user', $user);

        return $qb->getQuery();
    }

    public function findByApiKey($apiKey)
    {
        $qb = $this->createQueryBuilder('g')
                    ->where('g.apiKey = :apiKey')
                    ->setParameter('apiKey', $apiKey);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function queryBuilderPublicGardens()
    {
        $qb = $this->createQueryBuilder('g')
            ->where('g.isPublic = true');

        return $qb;
    }
}
