<?php

namespace CoreBundle\Repository;

/**
 * MeasurePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasurePostRepository extends \Doctrine\ORM\EntityRepository
{
}
