<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Garden;

/**
 * ShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryShareByGarden(Garden $garden)
    {
        $qb = $this->createQueryBuilder('s')
                ->where('s.garden = :garden')
                ->setParameter('garden', $garden);

        return $qb->getQuery();
    }
}
