<?php

namespace CoreBundle\Repository;

/**
 * UserShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserShareRepository extends \Doctrine\ORM\EntityRepository
{
}
