<?php

namespace CoreBundle\Repository;

/**
 * UserPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPostRepository extends \Doctrine\ORM\EntityRepository
{
}
