CoreBundle\Entity\UserShare:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        owner:
            expose: true
        message:
            expose: true
        createdAt:
            expose: true
    virtual_properties:
        garden:
            expose: true
            type: array
